version: "3.7"


services:

  src:
    build: ./src/
    container_name: parser_autoria
    command: sh -c "sleep 5s ; python3 ./main.py"
    depends_on:
      - db
    volumes:
      - ./dumps:${ROOT_DIR}/dumps
    env_file:
      - .env

  db:
    container_name: postgres
    image: postgres:15.3-alpine
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - .env